traces:
  configs:
    - name: default
      remote_write:
        - endpoint: tempo-eu-west-0.grafana.net:443
          basic_auth:
            username: 175079
            password: xxx
      receivers:
        otlp:
          protocols:
            http:
logs:
  configs:
    - name: default
      positions:
        filename: /mnt/ddev_config/grafana/positions.yaml
      scrape_configs:
        - job_name: drupal
          pipeline_stages:
            - json:
                expressions:
                  level: level_name
            - labels:
                level:
          static_configs:
            - targets: [localhost]
              labels:
                job: drupal
                __path__: /var/www/html/web/sites/default/files/private/logs/*log
      clients:
        - url: http://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
          basic_auth:
            username: 178566
            password: yyy
